"""
Canonical curated lists of supported Wellfound role and location slugs.
"""

# Categorized list of verified Wellfound SEO roles
SUPPORTED_WELLFOUND_ROLES: dict[str, str] = {
    "ai-engineer": "AI Engineer",
    "machine-learning-engineer": "Machine Learning Engineer",
    "deep-learning-engineer": "Deep Learning Engineer",
    "data-scientist": "Data Scientist",
    "data-engineer": "Data Engineer",
    "data-analyst": "Data Analyst",
    "ai-researcher": "AI Researcher",
    "prompt-engineer": "Prompt Engineer",
    "nlp-engineer": "NLP Engineer",
    "computer-vision-engineer": "Computer Vision Engineer",
    "robotics-engineer": "Robotics Engineer",
    "software-engineer": "Software Engineer",
    "senior-software-engineer": "Senior Software Engineer",
    "backend-engineer": "Backend Engineer",
    "frontend-engineer": "Frontend Engineer",
    "full-stack-engineer": "Full Stack Engineer",
    "mobile-developer": "Mobile Developer",
    "ios-developer": "iOS Developer",
    "android-developer": "Android Developer",
    "devops-engineer": "DevOps Engineer",
    "site-reliability-engineer": "Site Reliability Engineer (SRE)",
    "infrastructure-engineer": "Infrastructure Engineer",
    "security-engineer": "Security Engineer",
    "cloud-architect": "Cloud Architect",
    "systems-engineer": "Systems Engineer",
    "qa-engineer": "QA Engineer",
    "sdet": "SDET",
    "qa-automation-engineer": "QA Automation Engineer",
    "test-engineer": "Test Engineer",
    "engineering-manager": "Engineering Manager",
    "product-manager": "Product Manager",
    "technical-program-manager": "Technical Program Manager",
    "developer-advocate": "Developer Advocate",
    "solutions-architect": "Solutions Architect",
    "blockchain-developer": "Blockchain Developer",
    "intern": "Engineering Intern",
}

# Verifiable Wellfound locations
SUPPORTED_WELLFOUND_LOCATIONS: dict[str, str] = {
    "india": "All India",
    "bengaluru": "Bengaluru (Karnataka)",
    "pune": "Pune (Maharashtra)",
    "mumbai": "Mumbai (Maharashtra)",
    "delhi": "Delhi-NCR",
    "hyderabad": "Hyderabad (Telangana)",
    "chennai": "Chennai (Tamil Nadu)",
    "gurgaon": "Gurgaon (Haryana)",
    "noida": "Noida (Uttar Pradesh)",
    "remote": "Remote (Anywhere)",
    "united-states": "United States",
}

# Fuzzy synonym mapping to prevent 404/redirect errors on freeform input
ROLE_SYNONYMS: dict[str, str] = {
    "ai": "ai-engineer",
    "artificial intelligence": "ai-engineer",
    "llm": "ai-engineer",
    "genai": "ai-engineer",
    "generative ai": "ai-engineer",
    "ml": "machine-learning-engineer",
    "machine learning": "machine-learning-engineer",
    "data science": "data-scientist",
    "backend": "backend-engineer",
    "backend developer": "backend-engineer",
    "python": "backend-engineer",
    "python developer": "backend-engineer",
    "frontend": "frontend-engineer",
    "frontend developer": "frontend-engineer",
    "react": "frontend-engineer",
    "react developer": "frontend-engineer",
    "full stack": "full-stack-engineer",
    "fullstack": "full-stack-engineer",
    "full-stack": "full-stack-engineer",
    "software developer": "software-engineer",
    "swe": "software-engineer",
    "sde": "software-engineer",
    "sdet": "sdet",
    "qa": "qa-engineer",
    "quality assurance": "qa-engineer",
    "qa automation": "qa-automation-engineer",
    "devops": "devops-engineer",
    "sre": "site-reliability-engineer",
    "cloud": "cloud-architect",
    "infra": "infrastructure-engineer",
    "pm": "product-manager",
    "internship": "intern",
}

LOCATION_SYNONYMS: dict[str, str] = {
    "bangalore": "bengaluru",
    "bangalore, karnataka": "bengaluru",
    "bengaluru, karnataka": "bengaluru",
    "pune, maharashtra": "pune",
    "mumbai, maharashtra": "mumbai",
    "bombay": "mumbai",
    "delhi-ncr": "delhi",
    "new delhi": "delhi",
    "gurugram": "gurgaon",
    "hyderabad, telangana": "hyderabad",
    "chennai, tamil nadu": "chennai",
    "madras": "chennai",
    "all india": "india",
    "in": "india",
    "wfh": "remote",
    "anywhere": "remote",
    "work from home": "remote",
    "usa": "united-states",
    "us": "united-states",
}
